export const ADVERT_CREATE_REQUEST = 'ADVERT_CREATE_REQUEST';
export const ADVERT_CREATE_SUCCESS = 'ADVERT_CREATE_SUCCESS';
export const ADVERT_CREATE_FAILURE = 'ADVERT_CREATE_FAILURE';

export const ADVERT_UPDATE_REQUEST = 'ADVERT_UPDATE_REQUEST';
export const ADVERT_UPDATE_SUCCESS = 'ADVERT_UPDATE_SUCCESS';
export const ADVERT_UPDATE_FAILURE = 'ADVERT_UPDATE_FAILURE';

export const ADVERT_DELETE_REQUEST = 'ADVERT_DELETE_REQUEST';
export const ADVERT_DELETE_SUCCESS = 'ADVERT_DELETE_SUCCESS';
export const ADVERT_DELETE_FAILURE = 'ADVERT_DELETE_FAILURE';

export const ADVERT_REVIEW_CREATE_REQUEST = 'ADVERT_REVIEW_CREATE_REQUEST';
export const ADVERT_REVIEW_CREATE_SUCCESS = 'ADVERT_REVIEW_CREATE_SUCCESS';
export const ADVERT_REVIEW_CREATE_FAILURE = 'ADVERT_REVIEW_CREATE_FAILURE';
