export const ADVERTS_CATEGORY_REQUEST = 'ADVERTS_CATEGORY_REQUEST';
export const ADVERTS_CATEGORY_SUCCESS = 'ADVERTS_CATEGORY_SUCCESS';
export const ADVERTS_CATEGORY_FAILURE = 'ADVERTS_CATEGORY_FAILURE';