export const ADVERTS_LOADED_REQUEST = 'ADVERTS_LOADED_REQUEST';
export const ADVERTS_LOADED_SUCCESS = 'ADVERTS_LOADED_SUCCESS';
export const ADVERTS_LOADED_FAILURE = 'ADVERTS_LOADED_FAILURE';

export const USERADVERTS_LOADED_REQUEST = 'USERADVERTS_LOADED_REQUEST';
export const USERADVERTS_LOADED_SUCCESS = 'USERADVERTS_LOADED_SUCCESS';
export const USERADVERTS_LOADED_FAILURE = 'USERADVERTS_LOADED_FAILURE';
